name: Health check

on: 
  schedule: 
  # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * *'
    
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://pokedex-app-xi6e.onrender.com
          # Fail this action after this many failed attempts
          max-attempts: 3
          # Delay between retries
          retry-delay: 5s
          retry-all: no
